---
# Install dependencies
- name: Installing MySQL and Python development packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libmysqlclient-dev
    - python-dev
    - python-pip
    - git
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Install required python packages
  pip:
    name: "{{ item }}"
  with_items:
      - virtualenv
      - pexpect
