# Downloading and installing the code
- name: Clone repo
  git:
    repo: https://github.com/CitoEngine/cito_plugin_server
    dest: /opt/cito_plugin_server
    force: yes

- file:
    path: "{{ virtualenv }}"
    state: directory
    mode: 0755

- name: Create virtualenv
  shell: "virtualenv --no-site-packages {{ virtualenv }} && source {{ virtualenv }}/bin/activate && pip install -q --upgrade setuptools"
  args:
    executable: /bin/bash
    chdir: "{{ virtualenv }}"

- name: Edit /opt/cito_plugin_server/requirements.txt
  lineinfile:
    path: /opt/cito_plugin_server/requirements.txt
    regexp: 'distribute==0.6.45'
    line: 'distribute>0.6.45'

- name: Install requirements
  pip:
    requirements: /opt/cito_plugin_server/requirements.txt
    virtualenv: "{{ virtualenv }}"
